# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lnnWXRWbkQy5RAPfWBBFkVQyRHpbpwO
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

conn = sqlite3.connect('sales_data.db')

cursor = conn.cursor()


create_table_query = """
CREATE TABLE sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
"""


cursor.execute(create_table_query)


conn.commit()


conn.close()

print("Database 'sales_data.db' and table 'sales' created successfully!")

conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

insert_data_query = """
INSERT INTO sales (product, quantity, price) VALUES
('Laptop', 1, 1200.00),
('Mouse', 5, 25.00),
('Keyboard', 3, 75.00),
('Laptop', 2, 1150.50),
('Monitor', 2, 300.00),
('Mouse', 10, 22.75);
"""

cursor.execute(insert_data_query)
conn.commit()

print(" Data inserted successfully!")
conn.close()

conn = sqlite3.connect('sales_data.db')

query = """
SELECT product, SUM(quantity) AS total_quantity, SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY product;
"""
df = pd.read_sql_query(query, conn)
conn.close()
print(df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.bar(df['product'], df['total_revenue'], color='red')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Product')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

from google.colab import files

files.download('sales_chart.png')
files.download('sales_data.db')

